// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TopGrade")>]
[<assembly: AssemblyProductAttribute("TopGrade")>]
[<assembly: AssemblyDescriptionAttribute(".net code quality tool")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TopGrade"
    let [<Literal>] AssemblyProduct = "TopGrade"
    let [<Literal>] AssemblyDescription = ".net code quality tool"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
